# Generated by Django 4.2.29 on 2026-03-20 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workspace_collaboration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_workspa_2b1df8_idx',
            old_name='core_task_workspa_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_workspa_707abb_idx',
            old_name='core_task_workspa_priorit_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_workspa_65d84e_idx',
            old_name='core_task_workspa_assigne_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacemembership',
            new_name='core_worksp_workspa_46a682_idx',
            old_name='core_workspa_workspa_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Order within the same workspace column (status) for root tasks.'),
        ),
        migrations.AlterField(
            model_name='workspacemembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'status', 'position'], name='core_task_workspa_323426_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'parent'], name='core_task_workspa_0f236d_idx'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.task'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='core_taskco_task_id_b10483_idx'),
        ),
    ]
