# Generated by Django 4.2.29 on 2026-03-20 21:40

from django.db import migrations, models
import django.db.models.deletion


def forwards_board_data(apps, schema_editor):
    Workspace = apps.get_model("core", "Workspace")
    Board = apps.get_model("core", "Board")
    BoardColumn = apps.get_model("core", "BoardColumn")
    Task = apps.get_model("core", "Task")

    specs = [
        ("Backlog", 0, "todo", "#22c55e"),
        ("Ready", 1, "todo", "#3b82f6"),
        ("In progress", 2, "in_progress", "#ca8a04"),
        ("In review", 3, "in_progress", "#9333ea"),
        ("Done", 4, "done", "#ea580c"),
    ]
    status_to_col_index = {"todo": 0, "in_progress": 2, "done": 4}

    for ws in Workspace.objects.all():
        board = Board.objects.create(workspace=ws)
        cols = []
        for name, pos, st, color in specs:
            cols.append(
                BoardColumn.objects.create(
                    board=board,
                    name=name,
                    position=pos,
                    maps_to_status=st,
                    color=color,
                )
            )

        for t in Task.objects.filter(workspace=ws, parent__isnull=True):
            ix = status_to_col_index.get(t.status, 0)
            t.board_column_id = cols[ix].id
            t.save(update_fields=["board_column_id"])

        for t in Task.objects.filter(workspace=ws, parent__isnull=False):
            parent = Task.objects.filter(pk=t.parent_id).first()
            if parent and parent.board_column_id:
                t.board_column_id = parent.board_column_id
                t.save(update_fields=["board_column_id"])

    for col in BoardColumn.objects.all():
        roots = list(
            Task.objects.filter(board_column_id=col.id, parent__isnull=True).order_by(
                "position", "created_at"
            )
        )
        for i, t in enumerate(roots):
            Task.objects.filter(pk=t.pk).update(position=i)


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_task_kanban_comments_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BoardColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "wip_limit",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Max items in column (optional).",
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6b7280",
                        help_text="Hex color for column header dot.",
                        max_length=7,
                    ),
                ),
                (
                    "maps_to_status",
                    models.CharField(
                        choices=[
                            ("todo", "Todo"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                        ],
                        default="todo",
                        help_text="Coarse status used for API filters and task.status sync.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddField(
            model_name="board",
            name="workspace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board",
                to="core.workspace",
            ),
        ),
        migrations.AddField(
            model_name="boardcolumn",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="core.board",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="estimate",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Story points / rough estimate (e.g. 1–21).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="board_column",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="core.boardcolumn",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["workspace", "board_column", "position"],
                name="core_task_workspa_e8ef83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boardcolumn",
            index=models.Index(
                fields=["board", "position"],
                name="core_boardc_board_i_1817e1_idx",
            ),
        ),
        migrations.RunPython(forwards_board_data, backwards_noop),
        migrations.AlterField(
            model_name="task",
            name="board_column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="core.boardcolumn",
            ),
        ),
    ]
