# Generated by Django 4.2.29 on 2026-03-20 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_board_and_dynamic_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.boardcolumn'),
        ),
    ]
