# Generated by Django 4.2.29 on 2026-03-20 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('actor', models.CharField(blank=True, default='', help_text='Primary actor (e.g. Visitor, Admin).', max_length=120)),
                ('main_scenario', models.TextField(blank=True, default='', help_text='Main success scenario / description.')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_cases_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='core.workspace')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['workspace', 'position'], name='core_usecas_workspa_f07ae7_idx')],
            },
        ),
    ]
