# Generated by Django 4.2.29 on 2026-03-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_use_case'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UseCase',
        ),
    ]
